title: BCN Biobank Documentation
description: Welcome to the Breast Cancer Now Tissue Biobank documentation site. This site provides information regarding all the data, tools and resources managed and developed by the BCNTB Team.
remote_theme: just-the-docs/just-the-docs   # in github server
# theme: just-the-docs  # locally

url: https://pages.github.qmul.ac.uk/bci-btx-bioinfo/bcntb-doc.github.io/

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

callouts:
  highlight:
    title: Introduction
    color: red
    opacity: 0.2
