title: SNPnexus Documentation
description: Welcome to the SNPnexus documentation site. TThis repository provides information on the data, tools and resources developed and managed by the SNPnexus Team. s
theme: just-the-docs  # locally

url: https://pages.github.qmul.ac.uk/bci-btx-bioinfo/bcntb-doc.github.io/

aux_links:
  Documentation Repository: https://github.qmul.ac.uk/hfy344/snpnexus-doc.github.io

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
