name: Sync Documentation

# Define when to trigger the workflow
on:
  schedule:
    # This cron expression will run the workflow daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  sync-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.BCNTB_PAT_TOKEN }}

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.QMUL_SSH_KEY }}

      - name: Add Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.qmul.ac.uk >> ~/.ssh/known_hosts

      - name: Clone BCNTB Documentation
        run: |
          echo "Performing synchronisation..."
          git clone git@github.qmul.ac.uk:bci-btx-bioinfo/BCNTB-Documentation.git

      - name: Run generate docs script
        run: |
          cd bcntb-documentation
          bash generate_docs.sh ../BCNTB-Documentation  # Run generate docs script
          rm -rf ../BCNTB-Documentation

      - name: Configure Git User
        run: |
          git config --global user.email "actions@github.com"  # Default GitHub Actions email
          git config --global user.name "GitHub Actions"  # Default name for GitHub Actions

      - name: Stage Changes in Submodule
        run: |
          cd bcntb-documentation
          git checkout main || git checkout -b main    # Ensure on the 'main' branch in the submodule
          git pull origin main    # Pull the latest changes in case the branch is outdated
          git add .  # Stage all changes in the submodule
          git commit -m "Sync docs" || echo "No changes to commit"  # Commit changes, ignore if nothing to commit

      - name: Push changes in Submodule
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BCNTB_PAT_TOKEN }}
          branch: main

      - name: Stage Changes to Main Repo
        run: |
          git add bcntb-documentation  # Stage changes in the main repository
          git commit -m "Sync doc website" || echo "No changes to commit"

      - name: Push changes in Main Repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
